### ISSUE TITLE
Orb of Volatile Quicksilver (RB505)

### ISSUE THREAD

**Issue by Xanathar865** [BrandenEK/Blasphemous.LostDreams#55]
**TODO list**
- [ ] Code
- [ ] Text
- [x] Icon
- [ ] Location

**More information**
Description: This small perfectly spherical piece of quicksilver quivers with barely contained energy, awaiting only the right circumstances to burst forth with terrific force. Causes a destructive burst of energy about the Penitent One shortly after drinking a bile flask.
Effect: Shortly after the bile flask animation, an effect around the penitent one damages nearby enemies (perhaps a cante jondo explosion?)
Proposed Location: Received from Nacimiento upon completion of his quest.

**Comment by BrandenEK** [comment]
@ConanCimmerio This item will probably need a simple explosion animation.  Can you look into this?
@PenitentinWaiting @Xanathar865 This item is still missing text.
@NewbieElton Hopefully the code for this one should be fairly simple, adding an event handler for the flask drink, then spawning the vfx, then finding all IDamageable objects within a radius of the player

**Comment by BrandenEK** [comment]
This issue is being closed since it is now contained in the Nacimiento branch
